# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: edange
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: exam-ai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: exam-ai

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'prod'}
  environment:
    NODE_ENV: ${env:NODE_ENV}
    NODE_OPTIONS: ${env:NODE_OPTIONS}
    CLIENT_URL: ${env:CLIENT_URL}
    #EMAIL_USER: ${env:EMAIL_USER}
    #EMAIL_PASS: ${env:EMAIL_PASS}
    API_KEY: ${env:API_KEY}
    PORT: ${env:PORT}
    SERVERLESS: ${env:SERVERLESS}
    DB_URI: ${env:DB_URI}
    DB_NAME: ${env:DB_NAME}
    OPEN_AI_API_KEY: ${env:OPEN_AI_API_KEY}
    AWS_KEY_ID: ${env:AWS_KEY_ID}
    AWS_SECRET: ${env:AWS_SECRET}
    REGION: ${env:REGION}
    BUCKET_NAME: ${env:BUCKET_NAME}
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    RESEND_FROM_EMAIL: ${env:RESEND_FROM_EMAIL}
    SECRET: ${env:SECRET}

functions:
  api:
    handler: src/server.handler
    timeout: 30
    events:
      - httpApi: "*"
