openapi: 3.0.1
info:
  title: User Authentication API
  version: 1.0.0
tags:
  - name: Users
    description: Operations related to users
  - name: Authentication
    description: Operations related to authentication
  - name: Files
    description: Operations related to files
  - name: Games
    description: Operations related to competitive exam games
paths:
  /users:
    $ref: './docs/paths/user.yml#/root'
  /users/{id}:
    $ref: './docs/paths/user.yml#/id'
  /users/students/{userEmail}/{studentEmail}:
    $ref: './docs/paths/user.yml#/students'
  /auth/signin:
    $ref: './docs/paths/auth.yml#/signin'
  /auth/validate-email/{validationToken}:
    $ref: './docs/paths/auth.yml#/validate-email'
  /auth/resend-validation-token/{email}:
    $ref: './docs/paths/auth.yml#/resend-validation-token'
  /auth/send-reset-password-token/{email}:
    $ref: './docs/paths/auth.yml#/send-password-token'
  /auth/reset-password/{token}:
    $ref: './docs/paths/auth.yml#/reset-password'
  /auth/mobile/signup:
    $ref: './docs/paths/auth-mobile.yml#/signup'
  /auth/mobile/signin:
    $ref: './docs/paths/auth-mobile.yml#/signin'
  /auth/mobile/refresh:
    $ref: './docs/paths/auth-mobile.yml#/refresh'
  /auth/mobile/google:
    $ref: './docs/paths/auth-mobile.yml#/google'
  /auth/mobile/me:
    $ref: './docs/paths/auth-mobile.yml#/me'
  /files:
    $ref: './docs/paths/file.yml#/root'
  /files/{id}:
    $ref: './docs/paths/file.yml#/id'
  /games:
    $ref: './docs/paths/game.yml#/root'
  /games/{id}:
    $ref: './docs/paths/game.yml#/id'
  /games/{id}/accept:
    $ref: './docs/paths/game.yml#/accept'
  /games/{id}/start:
    $ref: './docs/paths/game.yml#/start'
  /games/{id}/time-limit:
    $ref: './docs/paths/game.yml#/time-limit'
  /games/{id}/play:
    $ref: './docs/paths/game.yml#/play'
  /games/{id}/submission:
    $ref: './docs/paths/game.yml#/submission'
  /games/{id}/result:
    $ref: './docs/paths/game.yml#/result'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      value: my-api-key
    MobileApiKeyAuth:
      type: apiKey
      in: header
      name: x-mobile-api-key
      value: my-mobile-api-key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    user:
      $ref: './docs/schemas/user.schemas.yml#/User'
    signIn:
      $ref: './docs/schemas/auth.schemas.yml#/SignIn'
    refreshToken:
      $ref: './docs/schemas/auth.schemas.yml#/RefreshToken'
    googleSignIn:
      $ref: './docs/schemas/auth.schemas.yml#/GoogleSignIn'
    file:
      $ref: './docs/schemas/file.schemas.yml#/File'
    game:
      $ref: './docs/schemas/game.schemas.yml#/Game'


